### ISSUE TITLE
Question about direction buffer format

### ISSUE THREAD

**Issue by wangchi87** [NVIDIAGameWorks/heightmap_rtx#1]
Hi, I am just wondering why direction buffer format can only be VK_FORMAT_R16G16B16A16_SFLOAT as the comment says.

```
typedef struct HrtxMapCreate
{
  ......
  // Currently only VK_FORMAT_R16G16B16A16_SFLOAT is supported
  VkDeviceOrHostAddressConstKHR directionsBuffer;
  ......
} HrtxMapCreate;
```

Looks like VK_FORMAT_R32G32B32_SFLOAT also works (using vertex normal buffer instead of creating another direction buffer).
Is there any potential problem that VK_FORMAT_R32G32B32_SFLOAT should be avoided?

BTW, I am with 551.70 beta driver and 4090.

**Comment by pknowlesnv** [comment]
Thanks for this, @wangchi87! These notes have been removed in 15c09927031f95ee587168aee16d1720c2f39cc2. Fp16 may save some memory but `VK_FORMAT_R32G32B32_SFLOAT` should work just fine with the latest vulkan beta drivers.
